services:
  db:
    image: postgres:latest
    container_name: service-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - service_db_data:/var/lib/postgresql/data
    networks:
      - golang-service-template-network

  redis:
    container_name: service-redis
    hostname: redis
    image: redis:latest
    volumes:
      - service_redis_data:/data
    restart: unless-stopped
    networks:
      - golang-service-template-network

  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    container_name: service-app
    ports:
      - "${SERVICE_PORT:-8000}:8000"
    volumes:
      - ./:/app:cached
    depends_on:
      - db
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT:-6379}
      DB_HOST: db
      DB_PORT: ${POSTGRES_PORT:-5432}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      GIN_MODE: "release"
    restart: unless-stopped
    networks:
      - golang-service-template-network

volumes:
  service_db_data:
    driver: local
  service_redis_data:
    driver: local

networks:
  golang-service-template-network:
    driver: bridge